server:
  port: 8080
  servlet:
    context-path: /@project.artifactId@
apiKey: 998723f9-1b09-465d-a67a-2a3b7f3e26c0
version: v1

uri:
  user: http://localhost:8082/mcs.user/user/v1
  auth: http://localhost:8081/mcs.auth/auth/v1